
# Copyright 2010 The Android Open Source Project

LOCAL_EXPORT_C_INCLUDE_DIRS := 
LOCAL_SRC_FILES := 
LOCAL_SRC_FILES_linux := 
LOCAL_MODULE := 
LOCAL_STATIC_LIBRARIES := 
LOCAL_C_INCLUDES := 
LOCAL_CFLAGS := 
LOCAL_MODULE_HOST_OS := 
